name: Deploy Pipeline
on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: watanabe
  ECS_CLUSTER: watanabe-cluster
  ECS_SERVICE: watanabe-service
  ECS_TASK_DEFINITION: src/.aws/task-definition.json

# AWS認証に必要
permissions:
  id-token: write # OIDCトークンを取得するために必要
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: src
    steps:
      - uses: actions/checkout@v4
      # TODO: Test

      - name: Build an Image
        run: docker image build -t temp_watanabe_image:latest .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the image to Amazon ECR
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker iamge tag temp_watanabe_image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}